// Code generated by "stringer -type=PollItemStatus -trimprefix=Status"; DO NOT EDIT.

package money

import "strconv"

const _PollItemStatus_name = "statusZeroInfoErrorFatalDisabledBusyWasResetCreditRejectedEscrowReturnRequestDispensed"

var _PollItemStatus_index = [...]uint8{0, 10, 14, 19, 24, 32, 36, 44, 50, 58, 64, 77, 86}

func (i PollItemStatus) String() string {
	if i >= PollItemStatus(len(_PollItemStatus_index)-1) {
		return "PollItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollItemStatus_name[_PollItemStatus_index[i]:_PollItemStatus_index[i+1]]
}
