// Code generated by "stringer -type=PollItemStatus"; DO NOT EDIT.

package money

import "strconv"

const _PollItemStatus_name = "statusZeroStatusInfoStatusErrorStatusFatalStatusDisabledStatusBusyStatusWasResetStatusCreditStatusRejectedStatusEscrowStatusReturnRequestStatusDispensed"

var _PollItemStatus_index = [...]uint8{0, 10, 20, 31, 42, 56, 66, 80, 92, 106, 118, 137, 152}

func (i PollItemStatus) String() string {
	if i >= PollItemStatus(len(_PollItemStatus_index)-1) {
		return "PollItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollItemStatus_name[_PollItemStatus_index[i]:_PollItemStatus_index[i+1]]
}
