#ifndef INCLUDE_CONFIG_H
#define INCLUDE_CONFIG_H

#define F_CPU 16000000UL  // Clock Speed

#define FIRMWARE_VERSION 0x0104
#define MDB_TIMEOUT_MS 6

#define MASTER_NOTIFY_DDR DDRB
#define MASTER_NOTIFY_PORT PORTB
#define MASTER_NOTIFY_PIN PINB2

#define LED_DDR DDRB
#define LED_PORT PORTB
#define LED_PIN PINB5

#endif  // INCLUDE_CONFIG_H
