// Code generated by "stringer -type=Features -trimprefix=Feature"; DO NOT EDIT.

package bill

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeatureFTL-1]
	_ = x[FeatureRecycling-2]
}

const _Features_name = "FTLRecycling"

var _Features_index = [...]uint8{0, 3, 12}

func (i Features) String() string {
	i -= 1
	if i >= Features(len(_Features_index)-1) {
		return "Features(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Features_name[_Features_index[i]:_Features_index[i+1]]
}
