// Code generated by "stringer -type=PollItemStatus"; DO NOT EDIT.

package bill

import "strconv"

const _PollItemStatus_name = "StatusInfoStatusErrorStatusFatalStatusBusyStatusDisabledStatusWasResetStatusRejectedStatusCreditStatusEscrow"

var _PollItemStatus_index = [...]uint8{0, 10, 21, 32, 42, 56, 70, 84, 96, 108}

func (i PollItemStatus) String() string {
	if i >= PollItemStatus(len(_PollItemStatus_index)-1) {
		return "PollItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollItemStatus_name[_PollItemStatus_index[i]:_PollItemStatus_index[i+1]]
}
