// Code generated by "stringer -type=EventKind -trimprefix=Event"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventInvalid-0]
	_ = x[EventInput-1]
	_ = x[EventMoney-2]
	_ = x[EventTime-3]
	_ = x[EventService-4]
	_ = x[EventCommand-5]
	_ = x[EventStop-6]
}

const _EventKind_name = "InvalidInputMoneyTimeServiceCommandStop"

var _EventKind_index = [...]uint8{0, 7, 12, 17, 21, 28, 35, 39}

func (i EventKind) String() string {
	if i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
