// Code generated by "stringer -type=State -trimprefix=State"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInvalid-0]
	_ = x[StateBoot-1]
	_ = x[StateBroken-2]
	_ = x[StateLocked-3]
	_ = x[StateFrontBegin-4]
	_ = x[StateFrontSelect-5]
	_ = x[StateFrontTune-6]
	_ = x[StateFrontAccept-7]
	_ = x[StateFrontTimeout-8]
	_ = x[StateFrontEnd-9]
	_ = x[StateServiceBegin-10]
	_ = x[StateServiceAuth-11]
	_ = x[StateServiceMenu-12]
	_ = x[StateServiceInventory-13]
	_ = x[StateServiceTest-14]
	_ = x[StateServiceReboot-15]
	_ = x[StateServiceEnd-16]
}

const _State_name = "InvalidBootBrokenLockedFrontBeginFrontSelectFrontTuneFrontAcceptFrontTimeoutFrontEndServiceBeginServiceAuthServiceMenuServiceInventoryServiceTestServiceRebootServiceEnd"

var _State_index = [...]uint8{0, 7, 11, 17, 23, 33, 44, 53, 64, 76, 84, 96, 107, 118, 134, 145, 158, 168}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
