// Code generated by "stringer -type=DeviceState -trimprefix=Device"; DO NOT EDIT.

package mdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceInvalid-0]
	_ = x[DeviceInited-1]
	_ = x[DeviceOnline-2]
	_ = x[DeviceReady-3]
	_ = x[DeviceError-4]
	_ = x[DeviceOffline-5]
}

const _DeviceState_name = "InvalidInitedOnlineReadyErrorOffline"

var _DeviceState_index = [...]uint8{0, 7, 13, 19, 24, 29, 36}

func (i DeviceState) String() string {
	if i >= DeviceState(len(_DeviceState_index)-1) {
		return "DeviceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceState_name[_DeviceState_index[i]:_DeviceState_index[i+1]]
}
