// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

package inventory

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State struct {
	Stocks               []*State_Stock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_23037db7bb8fe8db, []int{0}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetStocks() []*State_Stock {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type State_Stock struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Value                float32  `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State_Stock) Reset()         { *m = State_Stock{} }
func (m *State_Stock) String() string { return proto.CompactTextString(m) }
func (*State_Stock) ProtoMessage()    {}
func (*State_Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_state_23037db7bb8fe8db, []int{0, 0}
}
func (m *State_Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State_Stock.Unmarshal(m, b)
}
func (m *State_Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State_Stock.Marshal(b, m, deterministic)
}
func (dst *State_Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State_Stock.Merge(dst, src)
}
func (m *State_Stock) XXX_Size() int {
	return xxx_messageInfo_State_Stock.Size(m)
}
func (m *State_Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_State_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_State_Stock proto.InternalMessageInfo

func (m *State_Stock) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *State_Stock) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *State_Stock) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*State)(nil), "inventory.State")
	proto.RegisterType((*State_Stock)(nil), "inventory.State.Stock")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_state_23037db7bb8fe8db) }

var fileDescriptor_state_23037db7bb8fe8db = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0x49, 0x2c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0xcc, 0x2b, 0x4b, 0xcd, 0x2b, 0xc9,
	0x2f, 0xaa, 0x54, 0x6a, 0x61, 0xe4, 0x62, 0x0d, 0x06, 0x49, 0x09, 0xe9, 0x71, 0xb1, 0x15, 0x97,
	0xe4, 0x27, 0x67, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xe9, 0xc1, 0x55, 0xe9,
	0x81, 0x55, 0xe8, 0x05, 0x83, 0xa4, 0x83, 0xa0, 0xaa, 0xa4, 0xbc, 0x41, 0x1a, 0xf3, 0x93, 0xb3,
	0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xd4, 0xbc, 0xc4, 0xa4, 0x9c, 0xd4, 0x14, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0x8e, 0x20, 0x18, 0x57, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x59,
	0x81, 0x51, 0x83, 0x29, 0x08, 0xc2, 0x49, 0x62, 0x03, 0x3b, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x55, 0xab, 0xda, 0x72, 0xa7, 0x00, 0x00, 0x00,
}
