// Code generated by "stringer -type=EventKind -trimprefix=Event"; DO NOT EDIT.

package money

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventInvalid-0]
	_ = x[EventAbort-1]
	_ = x[EventCredit-2]
}

const _EventKind_name = "InvalidAbortCredit"

var _EventKind_index = [...]uint8{0, 7, 12, 18}

func (i EventKind) String() string {
	if i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
