// Code generated by "stringer -type=Command_t -trimprefix=COMMAND_"; DO NOT EDIT.

package mega

import "strconv"

const _Command_t_name = "STATUSCONFIGRESETDEBUGFLASHTWI_LISTENMDB_BUS_RESETMDB_TRANSACTION_SIMPLEMDB_TRANSACTION_CUSTOM"

var _Command_t_index = [...]uint8{0, 6, 12, 17, 22, 27, 37, 50, 72, 94}

func (i Command_t) String() string {
	i -= 1
	if i >= Command_t(len(_Command_t_index)-1) {
		return "Command_t(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Command_t_name[_Command_t_index[i]:_Command_t_index[i+1]]
}
