// Code generated by "stringer -type=Command_t -trimprefix=Command_"; DO NOT EDIT.

package mega

import "strconv"

const (
	_Command_t_name_0 = "PollConfigResetDebugFlash"
	_Command_t_name_1 = "MDB_Bus_ResetMDB_Transaction_SimpleMDB_Transaction_Custom"
)

var (
	_Command_t_index_0 = [...]uint8{0, 4, 10, 15, 20, 25}
	_Command_t_index_1 = [...]uint8{0, 13, 35, 57}
)

func (i Command_t) String() string {
	switch {
	case 1 <= i && i <= 5:
		i -= 1
		return _Command_t_name_0[_Command_t_index_0[i]:_Command_t_index_0[i+1]]
	case 7 <= i && i <= 9:
		i -= 7
		return _Command_t_name_1[_Command_t_index_1[i]:_Command_t_index_1[i+1]]
	default:
		return "Command_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
