// Code generated by "stringer -type=Command_t -trimprefix=COMMAND_"; DO NOT EDIT.

package mega

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[COMMAND_STATUS-1]
	_ = x[COMMAND_CONFIG-2]
	_ = x[COMMAND_RESET-3]
	_ = x[COMMAND_DEBUG-4]
	_ = x[COMMAND_FLASH-5]
	_ = x[COMMAND_MDB_BUS_RESET-7]
	_ = x[COMMAND_MDB_TRANSACTION_SIMPLE-8]
	_ = x[COMMAND_MDB_TRANSACTION_CUSTOM-9]
}

const (
	_Command_t_name_0 = "STATUSCONFIGRESETDEBUGFLASH"
	_Command_t_name_1 = "MDB_BUS_RESETMDB_TRANSACTION_SIMPLEMDB_TRANSACTION_CUSTOM"
)

var (
	_Command_t_index_0 = [...]uint8{0, 6, 12, 17, 22, 27}
	_Command_t_index_1 = [...]uint8{0, 13, 35, 57}
)

func (i Command_t) String() string {
	switch {
	case 1 <= i && i <= 5:
		i -= 1
		return _Command_t_name_0[_Command_t_index_0[i]:_Command_t_index_0[i+1]]
	case 7 <= i && i <= 9:
		i -= 7
		return _Command_t_name_1[_Command_t_index_1[i]:_Command_t_index_1[i+1]]
	default:
		return "Command_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
