// WARNING: This file has automatically been generated on Wed, 27 Feb 2019 11:38:05 +05.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mega

const (
	// COMMAND_MAX_LENGTH as defined in mega-firmware/main.h:30
	COMMAND_MAX_LENGTH = 93
	// RESPONSE_MAX_LENGTH as defined in mega-firmware/main.h:41
	RESPONSE_MAX_LENGTH = 80
	// RESPONSE_MASK_ERROR as defined in mega-firmware/main.h:43
	RESPONSE_MASK_ERROR = 128
)

// PROTOCOL_VERSION as declared in mega-firmware/main.h:15
const PROTOCOL_VERSION byte = 2

// MDB_STATE_IDLE as declared in mega-firmware/main.h:23
const MDB_STATE_IDLE Mdb_state_t = 0

// MDB_STATE_ERROR as declared in mega-firmware/main.h:24
const MDB_STATE_ERROR Mdb_state_t = 1

// MDB_STATE_SEND as declared in mega-firmware/main.h:25
const MDB_STATE_SEND Mdb_state_t = 2

// MDB_STATE_RECV as declared in mega-firmware/main.h:26
const MDB_STATE_RECV Mdb_state_t = 3

// MDB_STATE_RECV_END as declared in mega-firmware/main.h:27
const MDB_STATE_RECV_END Mdb_state_t = 4

// MDB_STATE_BUS_RESET as declared in mega-firmware/main.h:28
const MDB_STATE_BUS_RESET Mdb_state_t = 5

// COMMAND_STATUS as declared in mega-firmware/main.h:32
const COMMAND_STATUS Command_t = 1

// COMMAND_CONFIG as declared in mega-firmware/main.h:33
const COMMAND_CONFIG Command_t = 2

// COMMAND_RESET as declared in mega-firmware/main.h:34
const COMMAND_RESET Command_t = 3

// COMMAND_DEBUG as declared in mega-firmware/main.h:35
const COMMAND_DEBUG Command_t = 4

// COMMAND_FLASH as declared in mega-firmware/main.h:36
const COMMAND_FLASH Command_t = 5

// COMMAND_MDB_BUS_RESET as declared in mega-firmware/main.h:37
const COMMAND_MDB_BUS_RESET Command_t = 7

// COMMAND_MDB_TRANSACTION_SIMPLE as declared in mega-firmware/main.h:38
const COMMAND_MDB_TRANSACTION_SIMPLE Command_t = 8

// COMMAND_MDB_TRANSACTION_CUSTOM as declared in mega-firmware/main.h:39
const COMMAND_MDB_TRANSACTION_CUSTOM Command_t = 9

// RESPONSE_STATUS as declared in mega-firmware/main.h:44
const RESPONSE_STATUS Response_t = 1

// RESPONSE_JUST_RESET as declared in mega-firmware/main.h:46
const RESPONSE_JUST_RESET Response_t = 3

// RESPONSE_DEBUG as declared in mega-firmware/main.h:47
const RESPONSE_DEBUG Response_t = 4

// RESPONSE_TWI as declared in mega-firmware/main.h:48
const RESPONSE_TWI Response_t = 6

// RESPONSE_MDB_SUCCESS as declared in mega-firmware/main.h:49
const RESPONSE_MDB_SUCCESS Response_t = 8

// RESPONSE_BAD_PACKET as declared in mega-firmware/main.h:50
const RESPONSE_BAD_PACKET Response_t = 128

// RESPONSE_INVALID_CRC as declared in mega-firmware/main.h:51
const RESPONSE_INVALID_CRC Response_t = 129

// RESPONSE_INVALID_ID as declared in mega-firmware/main.h:52
const RESPONSE_INVALID_ID Response_t = 130

// RESPONSE_UNKNOWN_COMMAND as declared in mega-firmware/main.h:53
const RESPONSE_UNKNOWN_COMMAND Response_t = 131

// RESPONSE_INVALID_DATA as declared in mega-firmware/main.h:54
const RESPONSE_INVALID_DATA Response_t = 132

// RESPONSE_BUFFER_OVERFLOW as declared in mega-firmware/main.h:55
const RESPONSE_BUFFER_OVERFLOW Response_t = 133

// RESPONSE_NOT_IMPLEMENTED as declared in mega-firmware/main.h:56
const RESPONSE_NOT_IMPLEMENTED Response_t = 134

// RESPONSE_MDB_BUSY as declared in mega-firmware/main.h:57
const RESPONSE_MDB_BUSY Response_t = 136

// RESPONSE_MDB_INVALID_CHK as declared in mega-firmware/main.h:58
const RESPONSE_MDB_INVALID_CHK Response_t = 137

// RESPONSE_MDB_NAK as declared in mega-firmware/main.h:59
const RESPONSE_MDB_NAK Response_t = 138

// RESPONSE_MDB_TIMEOUT as declared in mega-firmware/main.h:60
const RESPONSE_MDB_TIMEOUT Response_t = 139

// RESPONSE_MDB_INVALID_END as declared in mega-firmware/main.h:61
const RESPONSE_MDB_INVALID_END Response_t = 140

// RESPONSE_MDB_RECEIVE_OVERFLOW as declared in mega-firmware/main.h:62
const RESPONSE_MDB_RECEIVE_OVERFLOW Response_t = 141

// RESPONSE_MDB_SEND_OVERFLOW as declared in mega-firmware/main.h:63
const RESPONSE_MDB_SEND_OVERFLOW Response_t = 142

// RESPONSE_MDB_CODE_ERROR as declared in mega-firmware/main.h:64
const RESPONSE_MDB_CODE_ERROR Response_t = 143

// RESPONSE_UART_READ_UNEXPECTED as declared in mega-firmware/main.h:65
const RESPONSE_UART_READ_UNEXPECTED Response_t = 144

// RESPONSE_UART_READ_ERROR as declared in mega-firmware/main.h:66
const RESPONSE_UART_READ_ERROR Response_t = 145

// RESPONSE_UART_READ_OVERFLOW as declared in mega-firmware/main.h:67
const RESPONSE_UART_READ_OVERFLOW Response_t = 146

// RESPONSE_UART_READ_PARITY as declared in mega-firmware/main.h:68
const RESPONSE_UART_READ_PARITY Response_t = 147

// RESPONSE_UART_SEND_BUSY as declared in mega-firmware/main.h:69
const RESPONSE_UART_SEND_BUSY Response_t = 148

// RESPONSE_TIMER_CODE_ERROR as declared in mega-firmware/main.h:70
const RESPONSE_TIMER_CODE_ERROR Response_t = 152

// FIELD_INVALID as declared in mega-firmware/main.h:74
const FIELD_INVALID Field_t = 0

// FIELD_PROTOCOL as declared in mega-firmware/main.h:75
const FIELD_PROTOCOL Field_t = 1

// FIELD_MCUSR as declared in mega-firmware/main.h:76
const FIELD_MCUSR Field_t = 2

// FIELD_BEEBEE as declared in mega-firmware/main.h:77
const FIELD_BEEBEE Field_t = 3

// FIELD_MDB_STAT as declared in mega-firmware/main.h:78
const FIELD_MDB_STAT Field_t = 4

// FIELD_TWI_STAT as declared in mega-firmware/main.h:79
const FIELD_TWI_STAT Field_t = 5

// FIELD_UART_STAT as declared in mega-firmware/main.h:80
const FIELD_UART_STAT Field_t = 6

// FIELD_QUEUE_MASTER as declared in mega-firmware/main.h:81
const FIELD_QUEUE_MASTER Field_t = 7

// FIELD_QUEUE_TWI as declared in mega-firmware/main.h:82
const FIELD_QUEUE_TWI Field_t = 8

// FIELD_MDB_PROTOCOL_STATE as declared in mega-firmware/main.h:83
const FIELD_MDB_PROTOCOL_STATE Field_t = 9

// FIELD_FIRMWARE_VERSION as declared in mega-firmware/main.h:84
const FIELD_FIRMWARE_VERSION Field_t = 10
