// WARNING: This file has automatically been generated on Fri, 01 Feb 2019 01:40:44 +05.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mega

const (
	// COMMAND_MAX_LENGTH as defined in i2c-mdb_atmega-gate/main.h:28
	COMMAND_MAX_LENGTH = 93
	// RESPONSE_MAX_LENGTH as defined in i2c-mdb_atmega-gate/main.h:39
	RESPONSE_MAX_LENGTH = 80
)

// MDB_State_Idle as declared in i2c-mdb_atmega-gate/main.h:20
const MDB_State_Idle MDB_State_t = 0

// MDB_State_Error as declared in i2c-mdb_atmega-gate/main.h:21
const MDB_State_Error MDB_State_t = 1

// MDB_State_Send as declared in i2c-mdb_atmega-gate/main.h:22
const MDB_State_Send MDB_State_t = 2

// MDB_State_Recv as declared in i2c-mdb_atmega-gate/main.h:23
const MDB_State_Recv MDB_State_t = 3

// MDB_State_Recv_End as declared in i2c-mdb_atmega-gate/main.h:24
const MDB_State_Recv_End MDB_State_t = 4

// MDB_State_Bus_Reset as declared in i2c-mdb_atmega-gate/main.h:25
const MDB_State_Bus_Reset MDB_State_t = 5

// Command_Poll as declared in i2c-mdb_atmega-gate/main.h:30
const Command_Poll Command_t = 1

// Command_Config as declared in i2c-mdb_atmega-gate/main.h:31
const Command_Config Command_t = 2

// Command_Reset as declared in i2c-mdb_atmega-gate/main.h:32
const Command_Reset Command_t = 3

// Command_Debug as declared in i2c-mdb_atmega-gate/main.h:33
const Command_Debug Command_t = 4

// Command_Flash as declared in i2c-mdb_atmega-gate/main.h:34
const Command_Flash Command_t = 5

// Command_MDB_Bus_Reset as declared in i2c-mdb_atmega-gate/main.h:35
const Command_MDB_Bus_Reset Command_t = 7

// Command_MDB_Transaction_Simple as declared in i2c-mdb_atmega-gate/main.h:36
const Command_MDB_Transaction_Simple Command_t = 8

// Command_MDB_Transaction_Custom as declared in i2c-mdb_atmega-gate/main.h:37
const Command_MDB_Transaction_Custom Command_t = 9

// Response_BeeBee as declared in i2c-mdb_atmega-gate/main.h:42
var Response_BeeBee [3]Response_t

// Response_Status as declared in i2c-mdb_atmega-gate/main.h:43
const Response_Status Response_t = 1

// Response_Debug as declared in i2c-mdb_atmega-gate/main.h:44
const Response_Debug Response_t = 4

// Response_TWI as declared in i2c-mdb_atmega-gate/main.h:45
const Response_TWI Response_t = 5

// Response_MDB_Started as declared in i2c-mdb_atmega-gate/main.h:46
const Response_MDB_Started Response_t = 8

// Response_MDB_Success as declared in i2c-mdb_atmega-gate/main.h:47
const Response_MDB_Success Response_t = 9

// Response_Error as declared in i2c-mdb_atmega-gate/main.h:49
const Response_Error Response_t = 128

// Response_Bad_Packet as declared in i2c-mdb_atmega-gate/main.h:50
const Response_Bad_Packet Response_t = 129

// Response_Invalid_CRC as declared in i2c-mdb_atmega-gate/main.h:51
const Response_Invalid_CRC Response_t = 130

// Response_Buffer_Overflow as declared in i2c-mdb_atmega-gate/main.h:52
const Response_Buffer_Overflow Response_t = 131

// Response_Unknown_Command as declared in i2c-mdb_atmega-gate/main.h:53
const Response_Unknown_Command Response_t = 132

// Response_Corruption as declared in i2c-mdb_atmega-gate/main.h:54
const Response_Corruption Response_t = 133

// Response_Not_Implemented as declared in i2c-mdb_atmega-gate/main.h:55
const Response_Not_Implemented Response_t = 134

// Response_MDB_Busy as declared in i2c-mdb_atmega-gate/main.h:56
const Response_MDB_Busy Response_t = 136

// Response_MDB_Invalid_CHK as declared in i2c-mdb_atmega-gate/main.h:57
const Response_MDB_Invalid_CHK Response_t = 137

// Response_MDB_NAK as declared in i2c-mdb_atmega-gate/main.h:58
const Response_MDB_NAK Response_t = 138

// Response_MDB_Timeout as declared in i2c-mdb_atmega-gate/main.h:59
const Response_MDB_Timeout Response_t = 139

// Response_MDB_Invalid_End as declared in i2c-mdb_atmega-gate/main.h:60
const Response_MDB_Invalid_End Response_t = 140

// Response_MDB_Receive_Overflow as declared in i2c-mdb_atmega-gate/main.h:61
const Response_MDB_Receive_Overflow Response_t = 141

// Response_MDB_Send_Overflow as declared in i2c-mdb_atmega-gate/main.h:62
const Response_MDB_Send_Overflow Response_t = 142

// Response_UART_Read_Unexpected as declared in i2c-mdb_atmega-gate/main.h:63
const Response_UART_Read_Unexpected Response_t = 144

// Response_UART_Read_Error as declared in i2c-mdb_atmega-gate/main.h:64
const Response_UART_Read_Error Response_t = 145

// Response_UART_Send_Busy as declared in i2c-mdb_atmega-gate/main.h:65
const Response_UART_Send_Busy Response_t = 146
