// Code generated by "stringer -type=Errcode_t -trimprefix=ERROR_"; DO NOT EDIT.

package mega

import "strconv"

const _Errcode_t_name = "BAD_PACKETINVALID_CRCINVALID_IDUNKNOWN_COMMANDINVALID_DATABUFFER_OVERFLOWNOT_IMPLEMENTEDRESPONSE_OVERWRITERESPONSE_EMPTY"

var _Errcode_t_index = [...]uint8{0, 10, 21, 31, 46, 58, 73, 88, 106, 120}

func (i Errcode_t) String() string {
	i -= 1
	if i >= Errcode_t(len(_Errcode_t_index)-1) {
		return "Errcode_t(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Errcode_t_name[_Errcode_t_index[i]:_Errcode_t_index[i+1]]
}
