// Code generated by "stringer -type=Field_t -trimprefix=FIELD_"; DO NOT EDIT.

package mega

import "strconv"

const _Field_t_name = "INVALIDPROTOCOLFIRMWARE_VERSIONERROR2ERRORNMCUSRCLOCK10UTWI_LENGTHTWI_DATAMDB_LENGTHMDB_RESULTMDB_DATAMDB_DURATION10U"

var _Field_t_index = [...]uint8{0, 7, 15, 31, 37, 43, 48, 56, 66, 74, 84, 94, 102, 117}

func (i Field_t) String() string {
	if i >= Field_t(len(_Field_t_index)-1) {
		return "Field_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Field_t_name[_Field_t_index[i]:_Field_t_index[i+1]]
}
