// Code generated by "stringer -type=Mdb_state_t -trimprefix=MDB_STATE_"; DO NOT EDIT.

package mega

import "strconv"

const _Mdb_state_t_name = "IDLEERRORSENDRECVRECV_ENDBUS_RESET"

var _Mdb_state_t_index = [...]uint8{0, 4, 9, 13, 17, 25, 34}

func (i Mdb_state_t) String() string {
	if i >= Mdb_state_t(len(_Mdb_state_t_index)-1) {
		return "Mdb_state_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mdb_state_t_name[_Mdb_state_t_index[i]:_Mdb_state_t_index[i+1]]
}
