// Code generated by "stringer -type=MDB_State_t -trimprefix=MDB_State_"; DO NOT EDIT.

package mega

import "strconv"

const _MDB_State_t_name = "IdleErrorSendRecvRecv_EndBus_Reset"

var _MDB_State_t_index = [...]uint8{0, 4, 9, 13, 17, 25, 34}

func (i MDB_State_t) String() string {
	if i >= MDB_State_t(len(_MDB_State_t_index)-1) {
		return "MDB_State_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MDB_State_t_name[_MDB_State_t_index[i]:_MDB_State_t_index[i+1]]
}
