// Code generated by "stringer -type=ResetFlag -trimprefix=ResetFlag"; DO NOT EDIT.

package mega

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResetFlagPowerOn-1]
	_ = x[ResetFlagExternal-2]
	_ = x[ResetFlagBrownOut-4]
	_ = x[ResetFlagWatchdog-8]
}

const (
	_ResetFlag_name_0 = "PowerOnExternal"
	_ResetFlag_name_1 = "BrownOut"
	_ResetFlag_name_2 = "Watchdog"
)

var (
	_ResetFlag_index_0 = [...]uint8{0, 7, 15}
)

func (i ResetFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ResetFlag_name_0[_ResetFlag_index_0[i]:_ResetFlag_index_0[i+1]]
	case i == 4:
		return _ResetFlag_name_1
	case i == 8:
		return _ResetFlag_name_2
	default:
		return "ResetFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
