// Code generated by "stringer -type=Response_t -trimprefix=RESPONSE_"; DO NOT EDIT.

package mega

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RESPONSE_OK-1]
	_ = x[RESPONSE_RESET-2]
	_ = x[RESPONSE_TWI_LISTEN-3]
	_ = x[RESPONSE_ERROR-128]
}

const (
	_Response_t_name_0 = "OKRESETTWI_LISTEN"
	_Response_t_name_1 = "ERROR"
)

var (
	_Response_t_index_0 = [...]uint8{0, 2, 7, 17}
)

func (i Response_t) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _Response_t_name_0[_Response_t_index_0[i]:_Response_t_index_0[i+1]]
	case i == 128:
		return _Response_t_name_1
	default:
		return "Response_t(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
