// WARNING: This file has automatically been generated on Wed, 27 Feb 2019 11:38:05 +05.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mega

// Mdb_state_t type as declared in mega-firmware/main.h:22
type Mdb_state_t byte

// Command_t type as declared in mega-firmware/main.h:31
type Command_t byte

// Response_t type as declared in mega-firmware/main.h:42
type Response_t byte

// Field_t type as declared in mega-firmware/main.h:73
type Field_t byte
