// WARNING: This file has automatically been generated on Wed, 30 Jan 2019 16:30:10 +05.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mega

// Command_t type as declared in i2c-mdb_atmega-gate/main.h:29
type Command_t byte

// Response_t type as declared in i2c-mdb_atmega-gate/main.h:40
type Response_t byte
