// WARNING: This file has automatically been generated on Fri, 01 Feb 2019 01:40:44 +05.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mega

// MDB_State_t type as declared in i2c-mdb_atmega-gate/main.h:19
type MDB_State_t byte

// Command_t type as declared in i2c-mdb_atmega-gate/main.h:29
type Command_t byte

// Response_t type as declared in i2c-mdb_atmega-gate/main.h:40
type Response_t byte
