#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
target=./cmd/mdb-cli/mdb-cli
gopkg=$(dirname $target)
name=$(basename $target)
remote="pi@pipi"
set -x
go test -v $gopkg ./hardware/mdb
GOARCH=arm GOOS=linux GOARM=6 go build -o $base/$target $gopkg
rsync -a $base/$target $remote:
ssh -t $remote ./$name
