#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
target=./cmd/vender/vender
gopkg=$(dirname $target)
name=$(basename $target)
remote="pi@pipi."
set -x
go test -v $gopkg ./head/...
GOARCH=arm GOOS=linux GOARM=6 go build -o $base/$target $gopkg
rsync -a $base/$target $base/vender.hcl $remote:
ssh -t $remote ./vender -config ./vender.hcl
