#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
remote="pi@pipi"
cd $base/hardware/i2c-mdb-atmega-gate/i2c-mdb_atmega-gate
set -x
make clean main.hex
rsync -a main.hex $remote:/tmp/
ssh -t $remote avrdude -p atmega328p -P usb -c dragon_isp -U flash:w:/tmp/main.hex
ssh -t $remote rm /tmp/main.hex
