#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
test_flag=(-race -timeout=11s)
: ${remote?"set env ssh deploy target"}
cd "$base"

go test "${test_flag[@]}" ./... >/dev/null || go test -v "${test_flag[@]}" ./...

script/build

rsync -a build/vender $remote:~/vender
cmd=$1 ; shift
#ssh -t $remote time sudo -n env GODEBUG=gctrace=1 chrt --fifo 99 \~/vender -config=local.hcl "$cmd" "$@"
ssh -t $remote time sudo -n \~/vender -config=local.hcl "$cmd" "$@"
