#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
target=./cmd/vender/vender
gopkg=$(dirname $target)
name=$(basename $target)
: ${remote="pi@pipi"}

echo "- run tests" >&2
set -x
go test ./... >/dev/null || go test -v ./...
GOARCH=arm GOOS=linux GOARM=6 go build -o $base/$target $gopkg
rsync -a $base/$target $base/vender.hcl $remote:~/
ssh -t $remote time sudo -n env GODEBUG=gctrace=1 chrt --fifo 99 \~/vender -config=\~/vender.hcl
