// Code generated by "stringer -type=CoinRouting -trimprefix=Routing"; DO NOT EDIT.

package coin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoutingCashBox-0]
	_ = x[RoutingTubes-1]
	_ = x[RoutingNotUsed-2]
	_ = x[RoutingReject-3]
}

const _CoinRouting_name = "CashBoxTubesNotUsedReject"

var _CoinRouting_index = [...]uint8{0, 7, 12, 19, 25}

func (i CoinRouting) String() string {
	if i >= CoinRouting(len(_CoinRouting_index)-1) {
		return "CoinRouting(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoinRouting_name[_CoinRouting_index[i]:_CoinRouting_index[i+1]]
}
