// Code generated by "stringer -type=DiagStatus -trimprefix=Diag"; DO NOT EDIT.

package coin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DiagPoweringUp-256]
	_ = x[DiagPoweringDown-512]
	_ = x[DiagOK-768]
	_ = x[DiagKeypadShifted-1024]
	_ = x[DiagManualActive-1296]
	_ = x[DiagNewInventoryInformation-1312]
	_ = x[DiagInhibited-1536]
	_ = x[DiagGeneralError-4096]
	_ = x[DiagGeneralChecksum1-4097]
	_ = x[DiagGeneralChecksum2-4098]
	_ = x[DiagGeneralVoltage-4099]
	_ = x[DiagDiscriminatorError-4352]
	_ = x[DiagDiscriminatorFlightOpen-4368]
	_ = x[DiagDiscriminatorReturnOpen-4369]
	_ = x[DiagDiscriminatorJam-4400]
	_ = x[DiagDiscriminatorBelowStandard-4417]
	_ = x[DiagDiscriminatorSensorA-4432]
	_ = x[DiagDiscriminatorSensorB-4433]
	_ = x[DiagDiscriminatorSensorC-4434]
	_ = x[DiagDiscriminatorTemperature-4435]
	_ = x[DiagDiscriminatorOptics-4436]
	_ = x[DiagAccepterError-4608]
	_ = x[DiagAccepterJam-4656]
	_ = x[DiagAccepterAlarm-4657]
	_ = x[DiagAccepterEmpty-4672]
	_ = x[DiagAccepterExitBeforeEnter-4688]
	_ = x[DiagSeparatorError-4864]
	_ = x[DiagSeparatorSortSensor-4880]
	_ = x[DiagDispenserError-5120]
	_ = x[DiagStorageError-5376]
	_ = x[DiagStorageCassetteRemoved-5378]
	_ = x[DiagStorageCashboxSensor-5379]
	_ = x[DiagStorageAmbientLight-5380]
}

const _DiagStatus_name = "PoweringUpPoweringDownOKKeypadShiftedManualActiveNewInventoryInformationInhibitedGeneralErrorGeneralChecksum1GeneralChecksum2GeneralVoltageDiscriminatorErrorDiscriminatorFlightOpenDiscriminatorReturnOpenDiscriminatorJamDiscriminatorBelowStandardDiscriminatorSensorADiscriminatorSensorBDiscriminatorSensorCDiscriminatorTemperatureDiscriminatorOpticsAccepterErrorAccepterJamAccepterAlarmAccepterEmptyAccepterExitBeforeEnterSeparatorErrorSeparatorSortSensorDispenserErrorStorageErrorStorageCassetteRemovedStorageCashboxSensorStorageAmbientLight"

var _DiagStatus_map = map[DiagStatus]string{
	256:  _DiagStatus_name[0:10],
	512:  _DiagStatus_name[10:22],
	768:  _DiagStatus_name[22:24],
	1024: _DiagStatus_name[24:37],
	1296: _DiagStatus_name[37:49],
	1312: _DiagStatus_name[49:72],
	1536: _DiagStatus_name[72:81],
	4096: _DiagStatus_name[81:93],
	4097: _DiagStatus_name[93:109],
	4098: _DiagStatus_name[109:125],
	4099: _DiagStatus_name[125:139],
	4352: _DiagStatus_name[139:157],
	4368: _DiagStatus_name[157:180],
	4369: _DiagStatus_name[180:203],
	4400: _DiagStatus_name[203:219],
	4417: _DiagStatus_name[219:245],
	4432: _DiagStatus_name[245:265],
	4433: _DiagStatus_name[265:285],
	4434: _DiagStatus_name[285:305],
	4435: _DiagStatus_name[305:329],
	4436: _DiagStatus_name[329:348],
	4608: _DiagStatus_name[348:361],
	4656: _DiagStatus_name[361:372],
	4657: _DiagStatus_name[372:385],
	4672: _DiagStatus_name[385:398],
	4688: _DiagStatus_name[398:421],
	4864: _DiagStatus_name[421:435],
	4880: _DiagStatus_name[435:454],
	5120: _DiagStatus_name[454:468],
	5376: _DiagStatus_name[468:480],
	5378: _DiagStatus_name[480:502],
	5379: _DiagStatus_name[502:522],
	5380: _DiagStatus_name[522:541],
}

func (i DiagStatus) String() string {
	if str, ok := _DiagStatus_map[i]; ok {
		return str
	}
	return "DiagStatus(" + strconv.FormatInt(int64(i), 10) + ")"
}
