// Code generated by "stringer -type=Features -trimprefix=Feature"; DO NOT EDIT.

package coin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeatureAlternativePayout-1]
	_ = x[FeatureExtendedDiagnostic-2]
	_ = x[FeatureControlledManualFillPayout-4]
	_ = x[FeatureFTL-8]
}

const (
	_Features_name_0 = "AlternativePayoutExtendedDiagnostic"
	_Features_name_1 = "ControlledManualFillPayout"
	_Features_name_2 = "FTL"
)

var (
	_Features_index_0 = [...]uint8{0, 17, 35}
)

func (i Features) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Features_name_0[_Features_index_0[i]:_Features_index_0[i+1]]
	case i == 4:
		return _Features_name_1
	case i == 8:
		return _Features_name_2
	default:
		return "Features(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
