// Code generated by "stringer -type=Features"; DO NOT EDIT.

package coin

import "strconv"

const (
	_Features_name_0 = "FeatureAlternativePayoutFeatureExtendedDiagnostic"
	_Features_name_1 = "FeatureControlledManualFillPayout"
	_Features_name_2 = "FeatureFTL"
)

var (
	_Features_index_0 = [...]uint8{0, 24, 49}
)

func (i Features) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Features_name_0[_Features_index_0[i]:_Features_index_0[i+1]]
	case i == 4:
		return _Features_name_1
	case i == 8:
		return _Features_name_2
	default:
		return "Features(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
