// Code generated by "stringer -type=PollItemStatus"; DO NOT EDIT.

package coin

import "strconv"

const _PollItemStatus_name = "StatusInfoStatusErrorStatusFatalStatusBusyStatusDispensedStatusDepositedStatusEscrowRequestStatusWasResetStatusRejectedStatusSlugs"

var _PollItemStatus_index = [...]uint8{0, 10, 21, 32, 42, 57, 72, 91, 105, 119, 130}

func (i PollItemStatus) String() string {
	if i >= PollItemStatus(len(_PollItemStatus_index)-1) {
		return "PollItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollItemStatus_name[_PollItemStatus_index[i]:_PollItemStatus_index[i+1]]
}
