// Code generated by "stringer -type=PollItemStatus"; DO NOT EDIT.

package coin

import "strconv"

const _PollItemStatus_name = "StatusInfoStatusErrorStatusFatalStatusDispensedStatusDepositedStatusEscrowRequestStatusWasResetStatusRejected"

var _PollItemStatus_index = [...]uint8{0, 10, 21, 32, 47, 62, 81, 95, 109}

func (i PollItemStatus) String() string {
	if i >= PollItemStatus(len(_PollItemStatus_index)-1) {
		return "PollItemStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollItemStatus_name[_PollItemStatus_index[i]:_PollItemStatus_index[i+1]]
}
